### ISSUE TITLE
Converting the library for proper support for MySqlClientFactory 

### ISSUE THREAD

**Issue by eByte23** [SapientGuardian/mysql-connector-net-netstandard#1]
This allows ORM's that utilise the DbInstance class to function.

I have done this work it is currently extremely messy but it works.
I'll cleanup what I have and submit a pr.

**Comment by SapientGuardian** [comment]
A PR would be great! That should make @MrBananaGuard happy too. (https://github.com/SapientGuardian/mysql-dnxcore50/issues/4)

**Comment by eByte23** [comment]
Currently available for testing on my nuget feed till I make a pr https://www.myget.org/F/ebyte-dotnetcore/api/v3/index.json

**Comment by SapientGuardian** [comment]
This is up as the official unofficial nuget package (https://www.nuget.org/packages/SapientGuardian.MySql.Data/) version 6.9.8-rc2-004. Thanks for your help!
