### ISSUE TITLE
MethodAccessException using library from .net 4.6.1 console app

### ISSUE THREAD

**Issue by SapientGuardian** [SapientGuardian/mysql-connector-net-netstandard#11]
```
Exception thrown: 'System.MethodAccessException' in SapientGuardian.MySql.Data.dll

Additional information: Attempt by security transparent method 'MySql.Data.Common.MyNetworkStream.CreateSocketStream(MySql.Data.MySqlClient.MySqlConnectionStringBuilder, System.Net.IPAddress, Boolean)' to access security critical method 'System.Net.Sockets.SocketTaskExtensions.ConnectAsync(System.Net.Sockets.Socket, System.Net.EndPoint)' failed.



Assembly 'SapientGuardian.MySql.Data, Version=6.9.8.0, Culture=neutral, PublicKeyToken=null' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.  Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.
```

**Comment by eByte23** [comment]
@SapientGuardian This could be could be to do with how the Connection is being made, its creating the connection async .Open() in Driver or something but there is no wait.

I put an ifdef for netstandard you could try that for 4.6.1
(All this assuming its not netstandard1.3 in 4.6.1)

**Comment by aharkness** [comment]
I believe this is still an issue, have the same problem using "SapientGuardian.EntityFrameworkCore.MySql": "7.1.21"

**Comment by SapientGuardian** [comment]
@aharkness Yes, this recently regressed. Have a look at https://github.com/SapientGuardian/mysql-connector-net-netstandard/issues/33 for discussion.

**Comment by aharkness** [comment]
ah, ok, thanks @SapientGuardian .  I can confirm that rolling back versions also fixed for me.
