### ISSUE TITLE
RTM support

### ISSUE THREAD

**Issue by Neerajvisma** [SapientGuardian/mysql-connector-net-netstandard#21]
.NET Core 1.0 RTM has been announced 2 days back and is available for use. I am planning to upgrade my application to it. I was wondering if "SapientGuardian.MySql.Data": "6.9.8-rc2-007", will work with it?

Thanks!

**Comment by eByte23** [comment]
Hi @Neerajvisma,

Please use the latest version 6.9.810 as this has been update for rtm and has some good bugfixes. Any version with the suffix of -rc2 is rc2 compatible and I can not say it will work or not it will work for rtm(it should in theory).

Thanks!
Elijah

**Comment by SapientGuardian** [comment]
I'm going to close this issue, but feel free to re-open it if you encounter difficulties specific to the RTM builds.
