### ISSUE TITLE
i still dont know how to connect ef core to mysql

### ISSUE THREAD

**Issue by HeikoZhang** [SapientGuardian/mysql-connector-net-netstandard#24]
thanks for your work, could you write a sample in vs2015 using ef core connecting to mysql DB?

**Comment by SapientGuardian** [comment]
Hi @HeikoZhang. I don't believe there's any way to use this library along with EF7, at least not without writing some sort of adapter code.

If you're not dead set on EF, I believe some folks are successfully using this library with Dapper.

**Comment by eByte23** [comment]
I'm testing an implmentation of mysql for EF7/EFCORE base on sqlite version I converted.
But its sorta a when a get time as I don't require this.

Also [NPoco ](https://github.com/schotime/NPoco) and [Dapper](https://github.com/StackExchange/dapper-dot-net) both works as ORM's as an alternative to EF7

**Comment by SapientGuardian** [comment]
It is now possible to use this library with EF through the provider library at https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql. Here's a sample project: https://github.com/SapientGuardian/AspNet5MultipleProject
