### ISSUE TITLE
MySql DateTime 0000-xx-xx xx:xx.xx

### ISSUE THREAD

**Issue by eByte23** [SapientGuardian/mysql-connector-net-netstandard#25]
With MySql its possible to have a daetime field that has a zero year.

When using an orm this doesn't map to datetime as lowest year in .net is 0001.
Should I Convert my date in query or should MySQL driver alter this to be 0001 when mapping to .net datetime type
*NOTE: This is existing in original driver.

**Comment by IntelOrca** [comment]
Its probably not a good idea to change this. In my own code I just have a function which will exchange the minimum MySql datetime with DateTime.MinValue and the maximum MySql with DateTime.MaxValue.

**Comment by eByte23** [comment]
@IntelOrca cool! wasn't sure what people were doing to get around this I'll just make a custom mapper for the datetime.

Cheers!
