### ISSUE TITLE
Transaction not rollbacked on Dispose

### ISSUE THREAD

**Issue by ghost** [SapientGuardian/mysql-connector-net-netstandard#30]
When used with EntityFrameworkCore, transactions are not rollbacked on Dispose.

In transaction.cs, the Dispose(bool) method is rollbacking the transaction. But as the method is not marked as `override`, it only hides the Dispose(bool) method from DbTransaction and will only be called if the type of the variable is MysqlTransaction.

```csharp
DbTransaction dbTransaction = new MysqlTransaction();
dbTransaction.Dispose(true); // calls DbTransaction.Dispose(bool);

MysqlTransaction mysqlTransaction = new MysqlTransaction();
mysqlTransaction.Dispose(true); // calls MysqlTransaction.Dispose(bool);
```

Therefore, when the RelationalTransaction from EntityFrameworkCore calls the Dispose method on it's _dbTransaction, it won't call the MysqlTransaction.Dispose(bool) method but the one from DbTransaction (that does nothing).

transaction.cs
```csharp
internal void Dispose(bool disposing)
    {
      if (disposing)
      {
        if ((conn != null && conn.State == ConnectionState.Open || conn.SoftClosed) && open)
          Rollback();
      }
    }
```

Fix:
transaction.cs
```csharp
protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
        if ((conn != null && conn.State == ConnectionState.Open || conn.SoftClosed) && open)
          Rollback();
      }
    }
```

**Comment by IntelOrca** [comment]
@cfinance Why don't you submit a PR instead?

**Comment by SapientGuardian** [comment]
Thanks for the report, I'll get this changed in the next couple days if nobody beats me to it with a PR.
